[tracer] Collecting data for ../apps/env-py3/intelligentDoor.py (pid=25238)
Downloading adxl345
Could not download adxl345
RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/EmailiPhoneNetworkPresence.py (pid=25264)
Encountered error: Traceback (most recent call last):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 255, in _runctx
    exec(cmd, globs, locs)
  File "../apps/env-py3/EmailiPhoneNetworkPresence.py", line 108, in <module>
    SMSlogfile = open('iphonescanSMSlog.txt', 'rw+')
ValueError: must have exactly one of create/read/write/append mode

RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/HomeControlCenterBBGW/HomeControlCenterBBGW.py (pid=25272)
Downloading flask_socketio
Process Process-3:
Traceback (most recent call last):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 255, in _runctx
    exec(cmd, globs, locs)
  File "../apps/env-py3/HomeControlCenterBBGW/HomeControlCenterBBGW.py", line 12, in <module>
    from flask_socketio import SocketIO, emit, join_room, leave_room, \
ImportError: No module named 'flask_socketio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 332, in start_tracer
    self._runctx(code, globs, None)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 277, in _runctx
    subprocess.check_output(["pip3", "install", "-qq", "--no-compile", "-t", "../libs/"+lib, lib])
  File "/tmp/libs/gevent/gevent/subprocess.py", line 320, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/tmp/libs/gevent/gevent/subprocess.py", line 555, in __init__
    restore_signals, start_new_session)
  File "/tmp/libs/gevent/gevent/subprocess.py", line 1300, in _execute_child
    data = errpipe_read.read()
  File "/tmp/libs/gevent/gevent/_fileobjectposix.py", line 107, in readall
    data = self.__read(DEFAULT_BUFFER_SIZE)
  File "/tmp/libs/gevent/gevent/_fileobjectposix.py", line 102, in __read
    self.hub.wait(self._read_event)
  File "/tmp/libs/gevent/gevent/hub.py", line 653, in wait
    raise InvalidSwitchError('Invalid switch into %s: %r (expected %r)' % (getcurrent(), result, unique))
gevent.hub.InvalidSwitchError: Invalid switch into <greenlet.greenlet object at 0x7f14e07cd5a0>: () (expected <object object at 0x7f14e2826230>)
0, 0
[tracer] Collecting data for ../apps/env-py3/RPiPIRSensor.py (pid=25315)
RPi-only (RuntimeError
RPi-only: 1
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/IoTRPiArduino/IoTRPiArduino.py (pid=25354)
RPi-only (RuntimeError
RPi-only: 1
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/NetworkMonitoringWithAWSIoT.py (pid=25365)
OSError: /root/key/root-CA.crt: Permission denied
RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/homeRoomTempHumMonitor.py (pid=25419)
RPi-only (RuntimeError
RPi-only: 1
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/smartScale/smartScale.py (pid=25426)
Trying to connect...
OSError: (113, 'No route to host')
RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/RPiRoomTempMonitorGnuplot.py (pid=25436)
Downloading Gnuplot
Could not download Gnuplot
RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/EchoPiWeather/EchoPiWeather.py (pid=25475)
Downloading pigpio
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Can't connect to pigpio at localhost(8888)

Did you start the pigpio daemon? E.g. sudo pigpiod

Did you specify the correct Pi host/port in the environment
variables PIGPIO_ADDR/PIGPIO_PORT?
E.g. export PIGPIO_ADDR=soft, export PIGPIO_PORT=8888

Did you specify the correct Pi host/port in the
pigpio.pi() function? E.g. pigpio.pi('soft', 8888)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Encountered error: Traceback (most recent call last):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 255, in _runctx
    exec(cmd, globs, locs)
  File "../apps/env-py3/EchoPiWeather/EchoPiWeather.py", line 16, in <module>
    s = DHT22.sensor(pi, 22, LED=16, power=8)
  File "../apps/env-py3/EchoPiWeather/DHT22.py", line 18, in __init__
    pi.write(power, 1) # Switch sensor on.
  File "/tmp/libs/pigpio/pigpio.py", line 1376, in write
    return _u2i(_pigpio_command(self.sl, _PI_CMD_WRITE, gpio, level))
  File "/tmp/libs/pigpio/pigpio.py", line 977, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

RPi-only: 0
successes: 0
0, 0
[tracer] Collecting data for ../apps/env-py3/WirelessDoorbell.py (pid=25519)
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
Process Process-11:
Traceback (most recent call last):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 332, in start_tracer
    self._runctx(code, globs, None)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 255, in _runctx
    exec(cmd, globs, locs)
  File "../apps/env-py3/WirelessDoorbell.py", line 9, in <module>
    from scapy.all import *
  File "/tmp/libs/scapy/scapy/all.py", line 40, in <module>
    from .layers.all import *
  File "/tmp/libs/scapy/scapy/layers/all.py", line 27, in <module>
    _import_star(_l)
  File "/tmp/libs/scapy/scapy/layers/all.py", line 20, in _import_star
    mod = importlib.import_module("scapy.layers." + m)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/libs/scapy/scapy/layers/dot11.py", line 19, in <module>
    from cryptography.hazmat.backends import default_backend
  File "/tmp/libs/jwt/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 3069, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 694, in add_entry
    for dist in find_distributions(entry, True):
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 2016, in find_on_path
    path_item_entries = _by_version_descending(os.listdir(path_item))
  File "/tmp/libs/jwt/pkg_resources/__init__.py", line 2000, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/tmp/libs/jwt/packaging/version.py", line 54, in __eq__
    return self._compare(other, lambda s, o: s == o)
  File "/tmp/libs/jwt/packaging/version.py", line 65, in _compare
    def _compare(self, other, method):
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 185, in tracer
    caller_name = caller_code.co_filename+":"+self._get_func_name(caller_code)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 160, in _get_func_name
    f = self._get_func(code)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/tracer.py", line 145, in _get_func
    funcs = [f for f in gc.get_referrers(code)
KeyboardInterrupt
Traceback (most recent call last):
  File "collect-callgraphs.py", line 89, in <module>
    p.join()
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/marcela/Research/lib-isolation/iot-app-analysis/callgraph-analysis/python35/Lib/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
